### ISSUE TITLE
Create node permissions

### ISSUE THREAD

**Issue by robotnic** [xmpp-ftw/xmpp-ftw-buddycloud#28] opened 2015-01-16 14:57 UTC
I have problems to create a node with this command.
(The user is loged in with username "arni")

{"type":0,"data":["xmpp.buddycloud.create",{"node":"/user/arni@laos.buddycloud.com/posts"}],"id":8}

The response is:

{"id":8,"type":1,"data":[{"type":"auth","condition":"forbidden"}]}

This is not what I expect but I don't know how to solve this problem.
Using this webinterface at
https://laos.buddycloud.com
I am able create the node.

The server permissions seam to be ok.
What's going on? Any idea?

**Comment by lloydwatkin** [comment] 2015-01-16 21:19
Not entirely sure where forbidden is coming from since we don't return this from the server (https://github.com/buddycloud/buddycloud-server-java/blob/master/src/main/java/org/buddycloud/channelserver/packetprocessor/iq/namespace/pubsub/set/NodeCreate.java), again @abmargb is needed to look at the logs.

**Comment by abmargb** [comment] 2015-01-21 14:27
I just managed to reproduce this in the hosted platform. Server logs for my request follow on. Notice that I receive two errors for the same request.

```xml
<iq type="set" to="cs.buddycloud.net" id="f6b2a8f7-e203-460c-87d0-c4ee23ec7765" from="abmar@abmarbarros.com/tigase-9">
   <pubsub xmlns="http://jabber.org/protocol/pubsub">
      <create node="/user/abmar@abmarbarros.com/chat" />
      <configure>
         <x xmlns="jabber:x:data" type="submit">
            <field var="FORM_TYPE" type="hidden">
               <value>http://jabber.org/protocol/pubsub#node_config</value>
            </field>
            <field var="buddycloud#channel_type">
               <value>topic</value>
            </field>
            <field var="pubsub#title">
               <value>Chat Topic Channel</value>
            </field>
            <field var="pubsub#access_model">
               <value>open</value>
            </field>
            <field var="buddycloud#default_affiliation">
               <value>publisher</value>
            </field>
         </x>
      </configure>
   </pubsub>
</iq>

<iq type="error" id="f6b2a8f7-e203-460c-87d0-c4ee23ec7765" from="cs.buddycloud.net" to="abmar@abmarbarros.com/tigase-9"><error code="403" type="auth">
   <forbidden xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
   </error>
</iq>

<iq type="error" id="f6b2a8f7-e203-460c-87d0-c4ee23ec7765" from="cs.buddycloud.net" to="abmar@abmarbarros.com/tigase-9"><error type="modify">
   <bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
   <nodeid-required xmlns="http://jabber.org/protocol/pubsub#errors"/></error>
</iq>
```

**Comment by abmargb** [comment] 2015-01-21 14:41
I suppose both ```actorIsRegistered()``` and ```nodeHandledByThisServer()``` in https://github.com/buddycloud/buddycloud-server-java/blob/master/src/main/java/org/buddycloud/channelserver/packetprocessor/iq/namespace/pubsub/set/NodeCreate.java#L53 need to be rewritten to consider multi-tenant deployments. I'm putting a PR for this.

**Comment by lloydwatkin** [comment] 2015-01-21 14:45
Yes I'd agree there :)
On hand to merge once ready.

Going to close this as its server related not xmpp-ftw related.

**Closed by lloydwatkin** 2015-01-21 14:45 UTC
